services:
  - type: web
    name: bookstore
    env: python
    plan: free
    # buildCommand: "./build.sh"
    startCommand: "gunicorn bookstore.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DJANGO_SETTINGS_MODULE
        value: bookstore.settings
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: CLOUDINARY_URL
        value: CLOUDINARY_URL=cloudinary://697955841318628:L1dddFGfRY2d0Fp4V78QU8f7pQQ@dfb4jsusf
