# Generated by Django 5.2.3 on 2025-08-17 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_remove_books_genre_books_genres'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_id', models.CharField(max_length=100, unique=True)),
                ('title', models.CharField(max_length=500)),
                ('authors', models.JSONField(default=list)),
                ('description', models.TextField(blank=True, null=True)),
                ('published_date', models.CharField(blank=True, max_length=20, null=True)),
                ('page_count', models.IntegerField(blank=True, null=True)),
                ('categories', models.JSONField(default=list)),
                ('average_rating', models.FloatField(blank=True, null=True)),
                ('ratings_count', models.IntegerField(default=0)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('preview_url', models.URLField(blank=True, null=True)),
                ('web_reader_url', models.URLField(blank=True, null=True)),
                ('is_ebook', models.BooleanField(default=False)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
